name: Backend Tests Only

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  GO_VERSION: '1.21'
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpass
  POSTGRES_DB: sharedcart_test
  DATABASE_URL: postgresql://testuser:testpass@localhost:5432/sharedcart_test?sslmode=disable

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        working-directory: ./sharedcart-backend
        run: go mod download

      - name: Create test env file
        working-directory: ./sharedcart-backend
        run: |
          cat > .env.test << EOF
          DB_HOST=localhost
          DB_PORT=5432
          DB_USER=${{ env.POSTGRES_USER }}
          DB_PASSWORD=${{ env.POSTGRES_PASSWORD }}
          DB_NAME=${{ env.POSTGRES_DB }}
          DB_SSL_MODE=disable
          JWT_SECRET=test_secret_key_for_ci
          JWT_EXPIRY_HOURS=24
          PORT=8080
          GIN_MODE=test
          ENV=test
          EOF

      - name: Run tests
        working-directory: ./sharedcart-backend
        run: |
          export $(cat .env.test | xargs)
          go test -v -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./sharedcart-backend/coverage.out
          flags: backend
          name: backend-coverage
          token: ${{ secrets.CODECOV_TOKEN }}